// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bingo_api.src.Context;

#nullable disable

namespace bingo_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250309234248_InitialDbData")]
    partial class InitialDbData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bingo_api.src.Entities.Accumulated", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activated")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CumulativePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IncrementBallCumulative")
                        .HasColumnType("boolean");

                    b.Property<int>("MaximumNumberOfBalls")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaximumValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("Accumulateds", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int[]>("Numbers")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("PunterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PunterId");

                    b.HasIndex("RoundId");

                    b.ToTable("Cards", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.CardWinner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PrizeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PrizeId");

                    b.ToTable("CardsWinners", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Prize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(15, 2)");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("Prizes", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Punter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(15, 2)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("Punters", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Recharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagemQrcode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PunterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Qrcode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(15, 2)");

                    b.HasKey("Id");

                    b.HasIndex("PunterId");

                    b.ToTable("Recharges", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.RoomSeller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("SellerId");

                    b.ToTable("RoomsSellers", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CardColumns")
                        .HasColumnType("integer");

                    b.Property<int>("CardRows")
                        .HasColumnType("integer");

                    b.Property<int>("CardSaleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("CardValue")
                        .HasColumnType("numeric(15, 2)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxBalls")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90);

                    b.Property<int[]>("Numbers")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Started")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TimeBetweenBalls")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4);

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Rounds", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(15, 2)");

                    b.Property<decimal>("Comission")
                        .HasColumnType("numeric(15, 2)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Sellers", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Accumulated", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Room", "Room")
                        .WithOne("Accumulated")
                        .HasForeignKey("bingo_api.src.Entities.Accumulated", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Card", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Punter", "Punter")
                        .WithMany("Cards")
                        .HasForeignKey("PunterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bingo_api.src.Entities.Round", "Round")
                        .WithMany("Cards")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Punter");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("bingo_api.src.Entities.CardWinner", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Card", "Card")
                        .WithMany("CardWinners")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bingo_api.src.Entities.Prize", "Prize")
                        .WithMany("CardWinners")
                        .HasForeignKey("PrizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Prize");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Prize", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Round", "Round")
                        .WithMany("Prizes")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Punter", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Seller", "Seller")
                        .WithMany("Punters")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Recharge", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Punter", "Punter")
                        .WithMany("Recharges")
                        .HasForeignKey("PunterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Punter");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Room", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Seller", "Owner")
                        .WithMany("OwnerRooms")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("bingo_api.src.Entities.RoomSeller", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Room", "Room")
                        .WithMany("RoomsSellers")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bingo_api.src.Entities.Seller", "Seller")
                        .WithMany("Rooms")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Round", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Room", "Room")
                        .WithMany("Rounds")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Card", b =>
                {
                    b.Navigation("CardWinners");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Prize", b =>
                {
                    b.Navigation("CardWinners");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Punter", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Recharges");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Room", b =>
                {
                    b.Navigation("Accumulated")
                        .IsRequired();

                    b.Navigation("RoomsSellers");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Round", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Prizes");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Seller", b =>
                {
                    b.Navigation("OwnerRooms");

                    b.Navigation("Punters");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
