// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bingo_api.src.Context;
using bingo_api.src.Entities.Scratch;
using bingo_api.src.Structs;

#nullable disable

namespace bingo_api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bingo_api.src.Entities.Accumulated", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activated")
                        .HasColumnType("boolean")
                        .HasColumnName("activated");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("CumulativePercentage")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cumulative_percentage");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("current_value");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IncrementBallCumulative")
                        .HasColumnType("boolean")
                        .HasColumnName("increment_ball_cumulative");

                    b.Property<int>("MaximumNumberOfBalls")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_number_of_balls");

                    b.Property<decimal>("MaximumValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("maximum_value");

                    b.Property<decimal>("MinimumValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("minimum_value");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("accumulateds", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Blockchain.Network", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChainId")
                        .HasColumnType("integer")
                        .HasColumnName("chain_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DiscardedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discarded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("RpcUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rpc_url");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("blockchain_networks", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Blockchain.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Decimals")
                        .HasColumnType("integer")
                        .HasColumnName("decimals");

                    b.Property<DateTime?>("DiscardedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discarded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsNative")
                        .HasColumnType("boolean")
                        .HasColumnName("is_native");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("blockchain_tokens", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Blockchain.TokenAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContractAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("contract_address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DiscardedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discarded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("NetworkId")
                        .HasColumnType("uuid")
                        .HasColumnName("network_id");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("NetworkId");

                    b.HasIndex("TokenId", "NetworkId")
                        .IsUnique()
                        .HasDatabaseName("ux_blockchain_token_addresses_token_network");

                    b.ToTable("blockchain_token_addresses", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.BotConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<double>("PresenceRate")
                        .HasColumnType("double precision")
                        .HasColumnName("presence_rate");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("bot_configs", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CardBuyId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_buy_id");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<int[]>("Numbers")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("numbers");

                    b.Property<Guid>("PunterId")
                        .HasColumnType("uuid")
                        .HasColumnName("punter_id");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CardBuyId");

                    b.HasIndex("PunterId");

                    b.HasIndex("RoundId");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.CardBuy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PunterId")
                        .HasColumnType("uuid")
                        .HasColumnName("punter_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("card_buys", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.CardWinner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PrizeId")
                        .HasColumnType("uuid")
                        .HasColumnName("prize_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PrizeId");

                    b.ToTable("cards_winners", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("QrCodeUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("qrcode_url");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Token")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Prize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(15, 2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("prizes", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Punter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(15, 2)")
                        .HasColumnName("balance");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_birth");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("IndicateTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("indicate_tag");

                    b.Property<bool>("IsBot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_bot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("PrizeBalance")
                        .HasColumnType("numeric(15, 2)")
                        .HasColumnName("prize_balance");

                    b.Property<string>("RegisteredWithTag")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("registered_with_tag");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_punters_email");

                    b.HasIndex("SellerId");

                    b.ToTable("punters", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Recharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18, 8)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("destination_address");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discarded_at");

                    b.Property<string>("ImagemQrcode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("imagem_qrcode");

                    b.Property<string>("Network")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("network");

                    b.Property<Guid>("PunterId")
                        .HasColumnType("uuid")
                        .HasColumnName("punter_id");

                    b.Property<string>("Qrcode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("qrcode");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("token");

                    b.Property<string>("TxHash")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tx_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(15, 2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("PunterId");

                    b.ToTable("recharges", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.RoomSeller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("assigned_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("SellerId");

                    b.ToTable("rooms_sellers", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CardColumns")
                        .HasColumnType("integer")
                        .HasColumnName("card_columns");

                    b.Property<int>("CardRows")
                        .HasColumnType("integer")
                        .HasColumnName("card_rows");

                    b.Property<int>("CardSaleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("card_sale_count");

                    b.Property<decimal>("CardValue")
                        .HasColumnType("numeric(15, 2)")
                        .HasColumnName("card_value");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished");

                    b.Property<int>("MaxBalls")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90)
                        .HasColumnName("max_balls");

                    b.Property<int[]>("Numbers")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("numbers");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("Started")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started");

                    b.Property<int>("TimeBetweenBalls")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4)
                        .HasColumnName("time_between_balls");

                    b.Property<List<TimelineEvent>>("Timeline")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("timeline");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("rounds", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Scratch.ScratchBuy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PunterId")
                        .HasColumnType("uuid")
                        .HasColumnName("punter_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SellerGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_game_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("scratch_buys", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Scratch.ScratchGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int[]>("AllowedMultipliers")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("allowed_multipliers");

                    b.Property<ScratchGameAttributes>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LayoutType")
                        .HasMaxLength(10)
                        .HasColumnType("integer")
                        .HasColumnName("layout_type");

                    b.Property<decimal>("MaxPrize")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("max_prize");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<decimal?>("Probability")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("probability");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("scratch_games", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Scratch.ScratchPrize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScratchGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("scratch_game_id");

                    b.Property<Guid>("ScratchTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("scratch_ticket_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ScratchGameId");

                    b.ToTable("scratch_prizes", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Scratch.ScratchSellerGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScratchGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("scratch_game_id");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ScratchGameId");

                    b.HasIndex("SellerId", "ScratchGameId")
                        .IsUnique();

                    b.ToTable("scratch_seller_games", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Scratch.ScratchTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<ScratchTicketAttributes>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Multiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("multiplier");

                    b.Property<decimal>("PrizeWon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("prize_won");

                    b.Property<Guid?>("PunterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Revealed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("revealed");

                    b.Property<Guid?>("ScratchBuyId")
                        .HasColumnType("uuid")
                        .HasColumnName("scratch_buy_id");

                    b.Property<Guid?>("ScratchPrizeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scratch_prize_id");

                    b.Property<Guid>("ScratchSellerGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("scratch_seller_game_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("PunterId");

                    b.HasIndex("ScratchBuyId");

                    b.HasIndex("ScratchPrizeId")
                        .IsUnique();

                    b.HasIndex("ScratchSellerGameId");

                    b.ToTable("scratch_tickets", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(15, 2)")
                        .HasColumnName("balance");

                    b.Property<decimal>("Comission")
                        .HasColumnType("numeric(15, 2)")
                        .HasColumnName("comission");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_birth");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<decimal>("IndicateRewardValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(15, 2)")
                        .HasDefaultValue(20m)
                        .HasColumnName("indicate_reward_value");

                    b.Property<decimal>("PrizeBalance")
                        .HasColumnType("numeric");

                    b.Property<SellerSettings>("Settings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("sellers", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.Shared.Withdrawal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("withdrawal_type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("withdrawals", (string)null);

                    b.HasDiscriminator<string>("withdrawal_type").HasValue("Withdrawal");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("bingo_api.src.Entities.TransactionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("current_balance");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("entity_type");

                    b.Property<decimal>("PreviousBalance")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("previous_balance");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("transaction_histories", (string)null);
                });

            modelBuilder.Entity("bingo_api.src.Entities.PunterWithdrawal", b =>
                {
                    b.HasBaseType("bingo_api.src.Entities.Shared.Withdrawal");

                    b.Property<Guid>("PunterId")
                        .HasColumnType("uuid");

                    b.HasIndex("PunterId");

                    b.HasDiscriminator().HasValue("Punter");
                });

            modelBuilder.Entity("bingo_api.src.Entities.SellerWithdrawal", b =>
                {
                    b.HasBaseType("bingo_api.src.Entities.Shared.Withdrawal");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.HasIndex("SellerId");

                    b.HasDiscriminator().HasValue("Seller");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Accumulated", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Room", "Room")
                        .WithOne("Accumulated")
                        .HasForeignKey("bingo_api.src.Entities.Accumulated", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accumulated_room_id");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Blockchain.TokenAddress", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Blockchain.Network", "Network")
                        .WithMany("TokenAddresses")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blockchain_token_addresses_network_id");

                    b.HasOne("bingo_api.src.Entities.Blockchain.Token", "Token")
                        .WithMany("TokenAddresses")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blockchain_token_addresses_token_id");

                    b.Navigation("Network");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("bingo_api.src.Entities.BotConfig", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Room", "Room")
                        .WithOne("BotConfig")
                        .HasForeignKey("bingo_api.src.Entities.BotConfig", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bot_config_room_id");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Card", b =>
                {
                    b.HasOne("bingo_api.src.Entities.CardBuy", "CardBuy")
                        .WithMany("Cards")
                        .HasForeignKey("CardBuyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_card_card_buy_id");

                    b.HasOne("bingo_api.src.Entities.Punter", "Punter")
                        .WithMany("Cards")
                        .HasForeignKey("PunterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_punter_id");

                    b.HasOne("bingo_api.src.Entities.Round", "Round")
                        .WithMany("Cards")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_round_id");

                    b.Navigation("CardBuy");

                    b.Navigation("Punter");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("bingo_api.src.Entities.CardWinner", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Card", "Card")
                        .WithMany("CardWinners")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_winner_card_id");

                    b.HasOne("bingo_api.src.Entities.Prize", "Prize")
                        .WithMany("CardWinners")
                        .HasForeignKey("PrizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_winner_prize_id");

                    b.Navigation("Card");

                    b.Navigation("Prize");
                });

            modelBuilder.Entity("bingo_api.src.Entities.PaymentMethod", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Seller", "Seller")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Prize", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Round", "Round")
                        .WithMany("Prizes")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prize_round_id");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Punter", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Seller", "Seller")
                        .WithMany("Punters")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Recharge", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Punter", "Punter")
                        .WithMany("Recharges")
                        .HasForeignKey("PunterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Punter");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Room", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Seller", "Owner")
                        .WithMany("OwnerRooms")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("bingo_api.src.Entities.RoomSeller", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Room", "Room")
                        .WithMany("RoomsSellers")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bingo_api.src.Entities.Seller", "Seller")
                        .WithMany("Rooms")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Round", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Room", "Room")
                        .WithMany("Rounds")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Scratch.ScratchPrize", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Scratch.ScratchGame", "ScratchGame")
                        .WithMany("ScratchPrizes")
                        .HasForeignKey("ScratchGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScratchGame");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Scratch.ScratchSellerGame", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Scratch.ScratchGame", "ScratchGame")
                        .WithMany("ScratchSellerGames")
                        .HasForeignKey("ScratchGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bingo_api.src.Entities.Seller", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScratchGame");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Scratch.ScratchTicket", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Punter", null)
                        .WithMany("ScratchTickets")
                        .HasForeignKey("PunterId");

                    b.HasOne("bingo_api.src.Entities.Scratch.ScratchBuy", "ScratchBuy")
                        .WithMany("ScratchTickets")
                        .HasForeignKey("ScratchBuyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("bingo_api.src.Entities.Scratch.ScratchPrize", "ScratchPrize")
                        .WithOne("ScratchTicket")
                        .HasForeignKey("bingo_api.src.Entities.Scratch.ScratchTicket", "ScratchPrizeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("bingo_api.src.Entities.Scratch.ScratchSellerGame", "ScratchSellerGame")
                        .WithMany("ScratchTickets")
                        .HasForeignKey("ScratchSellerGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScratchBuy");

                    b.Navigation("ScratchPrize");

                    b.Navigation("ScratchSellerGame");
                });

            modelBuilder.Entity("bingo_api.src.Entities.PunterWithdrawal", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Punter", "Punter")
                        .WithMany("Withdrawals")
                        .HasForeignKey("PunterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Punter");
                });

            modelBuilder.Entity("bingo_api.src.Entities.SellerWithdrawal", b =>
                {
                    b.HasOne("bingo_api.src.Entities.Seller", "Seller")
                        .WithMany("Withdrawals")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Blockchain.Network", b =>
                {
                    b.Navigation("TokenAddresses");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Blockchain.Token", b =>
                {
                    b.Navigation("TokenAddresses");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Card", b =>
                {
                    b.Navigation("CardWinners");
                });

            modelBuilder.Entity("bingo_api.src.Entities.CardBuy", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Prize", b =>
                {
                    b.Navigation("CardWinners");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Punter", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Recharges");

                    b.Navigation("ScratchTickets");

                    b.Navigation("Withdrawals");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Room", b =>
                {
                    b.Navigation("Accumulated")
                        .IsRequired();

                    b.Navigation("BotConfig")
                        .IsRequired();

                    b.Navigation("RoomsSellers");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Round", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Prizes");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Scratch.ScratchBuy", b =>
                {
                    b.Navigation("ScratchTickets");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Scratch.ScratchGame", b =>
                {
                    b.Navigation("ScratchPrizes");

                    b.Navigation("ScratchSellerGames");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Scratch.ScratchPrize", b =>
                {
                    b.Navigation("ScratchTicket")
                        .IsRequired();
                });

            modelBuilder.Entity("bingo_api.src.Entities.Scratch.ScratchSellerGame", b =>
                {
                    b.Navigation("ScratchTickets");
                });

            modelBuilder.Entity("bingo_api.src.Entities.Seller", b =>
                {
                    b.Navigation("OwnerRooms");

                    b.Navigation("PaymentMethods");

                    b.Navigation("Punters");

                    b.Navigation("Rooms");

                    b.Navigation("Withdrawals");
                });
#pragma warning restore 612, 618
        }
    }
}
